# Ambiente de desenvolvimento (H2 database)
  app:
    message:
      Arquivo de configuração do ${spring.application.name}

  spring:
    jpa:
      hibernate:
        ddl-auto:
          create
    datasource:
      url:
        jdbc:h2:mem:postt
      username:
        admin
      password:
      driver-class-name:
        org.h2.Driver
  server:
    port:
      8081

